# Generated by Django 4.1.2 on 2022-11-21 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studententrollment',
            name='entrolled_time',
        ),
        migrations.AddField(
            model_name='studententrollment',
            name='order_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
