# Generated by Django 4.1.2 on 2022-12-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_studententrollment_entrolled_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studententrollment',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
